name: Build and deploy docs

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install pandoc
      run: |
        sudo apt-get -y install pandoc
    - name: Set up Python
      with:
        python-version: '3.13'
      uses: actions/setup-python@v7.0.0
    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Install documentation dependencies
      run: uv sync --locked --all-groups
    - name: Build docs
      run: |
        cp NEWS.md docs/source
        uv run make -C docs html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
